### ISSUE TITLE
咨询

### ISSUE THREAD

**Issue by RivTian** [Borber/Allendance#2]
博主您好，请问您是怎么实现hugo用action做到自动部署？可以请教一下吗

**Comment by Borber** [comment]
> 博主您好，请问您是怎么实现hugo用action做到自动部署？可以请教一下吗

查看我的 blog 仓库

**Comment by RivTian** [comment]
已经解决了 文章参考：[Here](https://www.riotian.com/tech/%E4%BD%BF%E7%94%A8hugo+github-actions%E5%AE%9E%E7%8E%B0%E8%87%AA%E5%8A%A8%E5%8C%96%E9%83%A8%E7%BD%B2%E5%8D%9A%E5%AE%A2/)
